In [89]:
import pandas as pd
import re
import numpy as np

In [ ]:
df = pd.read_csv('./tabula-planningguide.csv', error_bad_lines=False)

In [6]:
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,· · · · · SOW SEEDS · · · · ·,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,Jan,Feb,Mar,Apr,May Jun Jul Aug,Sep,Oct,Nov,Dec
1,Basil,Asian greens,Asian greens,Asian,Asian Asian Soil is Broadbeans,Asian greens,Asian greens,Asian greens,Asian greens
2,Beans,Basil,Coriander,greens#,greens# greens# generally too Jerusalem,Beetroots,Basil*,Basil,Basil
3,Beetroots,Beetroots,Kale,Broadbeans,Broadbeans Broadbeans cold for artichokes,Broccoli,Beetroots,Beans,Beans
4,Broccoli,Broccoli,Leeks,Coriander,Garlic Jerusalem sowing Onions#,Coriander,Broccoli,Beetroots,Beetroots
5,NaN,NaN,NaN,NaN,NaN,NaN,#,#,NaN
6,Brussel,Brussel,Lettuce &,Garlic,Onions# artichokes seeds) Peas,Cabbages#,Cabbages,Cabbages,Cabbages#
7,sprouts,sprouts,salad greens,Onions#,Snow peas Onions# Silverbeet*,Carrots,Carrots,Capsicums,Capsicums
8,NaN,NaN,NaN,NaN,NaN,NaN,Capsicums*,Cauliflower#,Cauliflower#
9,Cabbages#,Cabbages#,Parsnips,Radishes,Spinach Peas Snow peas,Cauliflower#,Cauliflower#,Celery,Celery
10,Carrots,Carrots,Radishes,Snow peas,Spring Spring Spinach,Jerusalem,Celery*,Coriander,Cucumbers
11,Cauliflower#,Cauliflower#,Silverbeet,Spinach,onions onions Spring,artichokes,Coriander,Cucumbers,Eggplants
12,Celery,Celery,Spinach,Spring,onions*,Kale,Fennel,Eggplants,Fennel
13,Coriander,Coriander,Spring,onions,NaN,Leeks,Kale,Fennel,Kale
14,Kale,Kale,onions,NaN,NaN,Lettuce &,Leeks,Kale,Lettuce &
15,Lettuce &,Leeks,Turnips,NaN,NaN,salad greens,Lettuce &,Lettuce &,salad greens
16,salad greens,Lettuce &,NaN,NaN,NaN,Onions#,salad greens,salad greens,Potatoes
17,Potatoes,salad greens,NaN,NaN,NaN,Parsnips,Melons*,Peas,Pumpkins
18,Radishes,Parsnips,NaN,NaN,NaN,Peas,Parsnips,Potatoes,Radishes
19,Spring,Radishes,NaN,NaN,NaN,Potatoes,Peas,Pumpkins,Spring
20,NaN,NaN,NaN,NaN,NaN,NaN,Potatoes,Radishes,onions
21,onions,Silverbeet,NaN,NaN,NaN,Radishes,Pumpkins*,Spring,Sweetcorn
22,Turnips,Spinach,NaN,NaN,NaN,Silverbeet,Radishes,onions,Tomatoes
23,NaN,Spring,NaN,NaN,NaN,Snow peas,Silverbeet,Sweetcorn,Zucchini
24,NaN,onions,NaN,NaN,NaN,Spring,Spring,Tomatoes,NaN
25,NaN,Turnips,NaN,NaN,NaN,onions*,onions,Zucchini,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,Snow peas,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,Sweetcorn*,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,Tomatoes*,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,Zucchini*,NaN,NaN
30,NaN,NaN,NaN,NaN,· · · · · SOW SEEDS · · · · ·,NaN,NaN,NaN,NaN
31,Jan,Feb,Mar,Apr,May Jun Jul Aug,Sep,Oct,Nov,Dec
32,Basil,Asian,Asian greens,Asian,Asian Asian Asian Asian,Asian greens,Asian greens,Basil,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Basil
34,Beans,Greens,Beetroots,greens#,greens# greens# greens# greens#,Beetroots,Basil,Beans,Beans
35,Beetroots,Beetroots,Broccoli,Broadbeans,Broadbeans Broadbeans Jerusalem Capsicum*,Carrots,Beans,Beetroots,NaN
36,Broccoli*,Broccoli,Brussel,Coriander,Coriander Garlic artichokes Eggplants*,Celery,Beetroots,Celery,BeetrootsBroccoli*
37,Brussel,Brussel,Sprouts,Broccoli,Garlic Jerusalem Jerusalem,Coriander,Carrots,Cucumbers,NaN
38,Sprouts*,Sprouts,Cabbages#,Cauliflower#,Lettuce & artichokes artichokes,Jerusalem,Coriander,Fennel,Brussel
39,NaN,NaN,NaN,NaN,NaN,NaN,Celery,Lettuce &,sprouts*
40,Cabbage*,Cabbages#,Carrots,Kale,salad Lettuce & Leeks*,artichokes,Cucumbers,salad greens,Cabbage*
41,Caulifower#*,Carrots,Cauliflower#,Lettuce &,greens# salad Lettuce &,Leeks,Fennel,Potatoes,Cauliflower#*
42,Coriander,Cauliflower#,Kale,salad,Peas greens# salad,Lettuce &,Leeks,Pumpkins,Celery
43,Kale*,Coriander,Leeks,greens#,Snow peas Snow peas greens#,salad greens,Lettuce &,Radishes,Cucumbers
44,Lettuce &,English,Lettuce &,Onions,Spinach Parsnip,Melons*,salad greens,Spring,Lettuce &
45,salad greens,Fennel,salad greens,Radishes,Spring Peas,Parsnips,Melons,onions,salad greens
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Potatoes
47,Sweetcorn,Kale,Radishes,Silverbeet,onions Radishes,Peas,Parsnips,Sweetcorn,Pumpkins
48,NaN,Leeks,Silverbeet,Spinach,Radish,Potatoes,Peas,Tomatoes,NaN
49,NaN,Lettuce &,Spinach,Spring,Silverbeet,Pumpkins*,Potatoes,NaN,RadishesSweetcorn
50,NaN,salad greens,Spring,onions,Snow peas,Radishes,Pumpkins,NaN,NaN
51,NaN,Parsnips,onions*,Turnips,Spinach,Silverbeet,Radishes,NaN,Spring
52,NaN,NaN,NaN,NaN,NaN,NaN,Silverbeet,NaN,onions
53,NaN,Radishes,Turnips,NaN,Spring,Snow peas,Snow peas,NaN,Tomatoes
54,NaN,Spinach,NaN,NaN,onions*,Spring,Spring,NaN,NaN
55,NaN,Swedes,NaN,NaN,Tomatoes*,onions,onions,NaN,NaN
56,NaN,Turnips,NaN,NaN,NaN,Tomatoes*,Sweet corn,NaN,NaN
57,NaN,NaN,NaN,NaN,NaN,NaN,Tomatoes,NaN,NaN
58,NaN,NaN,NaN,NaN,NaN,NaN,Zucchini,NaN,NaN

In [10]:
df.columns = df.iloc[0]

In [11]:
df.head()

,Jan,Feb,Mar,Apr,May Jun Jul Aug,Sep,Oct,Nov,Dec
0,Jan,Feb,Mar,Apr,May Jun Jul Aug,Sep,Oct,Nov,Dec
1,Basil,Asian greens,Asian greens,Asian,Asian Asian Soil is Broadbeans,Asian greens,Asian greens,Asian greens,Asian greens
2,Beans,Basil,Coriander,greens#,greens# greens# generally too Jerusalem,Beetroots,Basil*,Basil,Basil
3,Beetroots,Beetroots,Kale,Broadbeans,Broadbeans Broadbeans cold for artichokes,Broccoli,Beetroots,Beans,Beans
4,Broccoli,Broccoli,Leeks,Coriander,Garlic Jerusalem sowing Onions#,Coriander,Broccoli,Beetroots,Beetroots

In [18]:
df[['May', 'Jun', 'Jul', 'Aug']] = df['May Jun Jul Aug'].str.split(' ', 3, expand=True)

In [20]:
df.drop('May Jun Jul Aug', axis=1, inplace=True)

In [26]:
df1 = df.iloc[1:29]

In [27]:
df1

,Jan,Feb,Mar,Apr,Sep,Oct,Nov,Dec,May,Jun,Jul,Aug
2,Beans,Basil,Coriander,greens#,Beetroots,Basil*,Basil,Basil,greens#,,greens#,generally too Jerusalem
3,Beetroots,Beetroots,Kale,Broadbeans,Broccoli,Beetroots,Beans,Beans,Broadbeans,Broadbeans,cold,for artichokes
4,Broccoli,Broccoli,Leeks,Coriander,Coriander,Broccoli,Beetroots,Beetroots,Garlic,Jerusalem,sowing,Onions#
5,NaN,NaN,NaN,NaN,NaN,#,#,NaN,NaN,NaN,NaN,NaN
6,Brussel,Brussel,Lettuce &,Garlic,Cabbages#,Cabbages,Cabbages,Cabbages#,Onions#,artichokes,seeds),Peas
7,sprouts,sprouts,salad greens,Onions#,Carrots,Carrots,Capsicums,Capsicums,Snow,peas,Onions#,Silverbeet*
8,NaN,NaN,NaN,NaN,NaN,Capsicums*,Cauliflower#,Cauliflower#,NaN,NaN,NaN,NaN
9,Cabbages#,Cabbages#,Parsnips,Radishes,Cauliflower#,Cauliflower#,Celery,Celery,Spinach,Peas,Snow,peas
10,Carrots,Carrots,Radishes,Snow peas,Jerusalem,Celery*,Coriander,Cucumbers,Spring,Spring,Spinach,None
11,Cauliflower#,Cauliflower#,Silverbeet,Spinach,artichokes,Coriander,Cucumbers,Eggplants,onions,onions,Spring,None
12,Celery,Celery,Spinach,Spring,Kale,Fennel,Eggplants,Fennel,onions*,None,None,None
13,Coriander,Coriander,Spring,onions,Leeks,Kale,Fennel,Kale,NaN,NaN,NaN,NaN
14,Kale,Kale,onions,NaN,Lettuce &,Leeks,Kale,Lettuce &,NaN,NaN,NaN,NaN
15,Lettuce &,Leeks,Turnips,NaN,salad greens,Lettuce &,Lettuce &,salad greens,NaN,NaN,NaN,NaN
16,salad greens,Lettuce &,NaN,NaN,Onions#,salad greens,salad greens,Potatoes,NaN,NaN,NaN,NaN
17,Potatoes,salad greens,NaN,NaN,Parsnips,Melons*,Peas,Pumpkins,NaN,NaN,NaN,NaN
18,Radishes,Parsnips,NaN,NaN,Peas,Parsnips,Potatoes,Radishes,NaN,NaN,NaN,NaN
19,Spring,Radishes,NaN,NaN,Potatoes,Peas,Pumpkins,Spring,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,Potatoes,Radishes,onions,NaN,NaN,NaN,NaN
21,onions,Silverbeet,NaN,NaN,Radishes,Pumpkins*,Spring,Sweetcorn,NaN,NaN,NaN,NaN
22,Turnips,Spinach,NaN,NaN,Silverbeet,Radishes,onions,Tomatoes,NaN,NaN,NaN,NaN
23,NaN,Spring,NaN,NaN,Snow peas,Silverbeet,Sweetcorn,Zucchini,NaN,NaN,NaN,NaN
24,NaN,onions,NaN,NaN,Spring,Spring,Tomatoes,NaN,NaN,NaN,NaN,NaN
25,NaN,Turnips,NaN,NaN,onions*,onions,Zucchini,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,Snow peas,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,Sweetcorn*,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,Tomatoes*,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,Zucchini*,NaN,NaN,NaN,NaN,NaN,NaN

In [66]:
df1=df1.replace('\*','',regex=True)

In [67]:
df1

,Jan,Feb,Mar,Apr,Sep,Oct,Nov,Dec,May,Jun,Jul,Aug
2,Beans,Basil,Coriander,greens#,Beetroots,Basil,Basil,Basil,greens#,,greens#,generally too Jerusalem
3,Beetroots,Beetroots,Kale,Broadbeans,Broccoli,Beetroots,Beans,Beans,Broadbeans,Broadbeans,cold,for artichokes
4,Broccoli,Broccoli,Leeks,Coriander,Coriander,Broccoli,Beetroots,Beetroots,Garlic,Jerusalem,sowing,Onions#
5,nan,nan,nan,nan,nan,#,#,nan,nan,nan,nan,nan
6,Brussel,Brussel,Lettuce &,Garlic,Cabbages#,Cabbages,Cabbages,Cabbages#,Onions#,artichokes,seeds),Peas
7,sprouts,sprouts,salad greens,Onions#,Carrots,Carrots,Capsicums,Capsicums,Snow,peas,Onions#,Silverbeet
8,nan,nan,nan,nan,nan,Capsicums,Cauliflower#,Cauliflower#,nan,nan,nan,nan
9,Cabbages#,Cabbages#,Parsnips,Radishes,Cauliflower#,Cauliflower#,Celery,Celery,Spinach,Peas,Snow,peas
10,Carrots,Carrots,Radishes,Snow peas,Jerusalem,Celery,Coriander,Cucumbers,Spring,Spring,Spinach,None
11,Cauliflower#,Cauliflower#,Silverbeet,Spinach,artichokes,Coriander,Cucumbers,Eggplants,onions,onions,Spring,None
12,Celery,Celery,Spinach,Spring,Kale,Fennel,Eggplants,Fennel,onions,None,None,None
13,Coriander,Coriander,Spring,onions,Leeks,Kale,Fennel,Kale,nan,nan,nan,nan
14,Kale,Kale,onions,nan,Lettuce &,Leeks,Kale,Lettuce &,nan,nan,nan,nan
15,Lettuce &,Leeks,Turnips,nan,salad greens,Lettuce &,Lettuce &,salad greens,nan,nan,nan,nan
16,salad greens,Lettuce &,nan,nan,Onions#,salad greens,salad greens,Potatoes,nan,nan,nan,nan
17,Potatoes,salad greens,nan,nan,Parsnips,Melons,Peas,Pumpkins,nan,nan,nan,nan
18,Radishes,Parsnips,nan,nan,Peas,Parsnips,Potatoes,Radishes,nan,nan,nan,nan
19,Spring,Radishes,nan,nan,Potatoes,Peas,Pumpkins,Spring,nan,nan,nan,nan
20,nan,nan,nan,nan,nan,Potatoes,Radishes,onions,nan,nan,nan,nan
21,onions,Silverbeet,nan,nan,Radishes,Pumpkins,Spring,Sweetcorn,nan,nan,nan,nan
22,Turnips,Spinach,nan,nan,Silverbeet,Radishes,onions,Tomatoes,nan,nan,nan,nan
23,nan,Spring,nan,nan,Snow peas,Silverbeet,Sweetcorn,Zucchini,nan,nan,nan,nan
24,nan,onions,nan,nan,Spring,Spring,Tomatoes,nan,nan,nan,nan,nan
25,nan,Turnips,nan,nan,onions,onions,Zucchini,nan,nan,nan,nan,nan
26,nan,nan,nan,nan,nan,Snow peas,nan,nan,nan,nan,nan,nan
27,nan,nan,nan,nan,nan,Sweetcorn,nan,nan,nan,nan,nan,nan
28,nan,nan,nan,nan,nan,Tomatoes,nan,nan,nan,nan,nan,nan
29,nan,nan,nan,nan,nan,Zucchini,nan,nan,nan,nan,nan,nan

In [52]:
jan = list(df1['Jan'].unique())

In [53]:
feb = list(df1['Feb'].unique())

In [54]:
mar = list(df['Mar'].unique())

In [55]:
apr = list(df1['Apr'].unique())

In [56]:
may = list(df1['May'].unique())

In [57]:
jun = list(df1['Jun'].unique())

In [58]:
jul = list(df1['Jul'].unique())

In [59]:
aug = list(df1['Aug'].unique())

In [60]:
sep = list(df1['Sep'].unique())

In [61]:
octo = list(df1['Oct'].unique())

In [62]:
nov = list(df1['Nov'].unique())

In [63]:
dec = list(df1['Dec'].unique())

In [64]:
final = []
final = jan + feb + mar +apr + may + jun + jul + aug + sep + octo + nov + dec

In [68]:
final = [x for x in final if str(x) != 'nan']

In [79]:
removetable = str.maketrans('', '', '@*#%&')
out_list = [s.translate(removetable) for s in final]

In [81]:
out_list = list(filter(None, out_list))

In [86]:
out_list = sorted(out_list)

In [91]:
out_list

array(['Asian greens', 'Basil', 'Beans', 'Beetroots', 'Broadbeans',
       'Broccoli', 'Brussel', 'Cabbages', 'Capsicums', 'Carrots',
       'Cauliflower', 'Celery', 'Coriander', 'Cucumbers', 'Eggplants',
       'Fennel', 'Garlic', 'Jerusalem', 'Kale', 'Leeks', 'Lettuce ',
       'Mar', 'Melons', 'None', 'Onions', 'Parsnips', 'Peas', 'Potatoes',
       'Pumpkins', 'Radishes', 'Silverbeet', 'Snow', 'Snow peas',
       'Spinach', 'Spring', 'Sprouts', 'Sweetcorn', 'Tomatoes', 'Turnips',
       'Zucchini', 'artichokes', 'cold', 'for artichokes',
       'generally too Jerusalem', 'greens', 'onions', 'peas',
       'salad greens', 'seeds)', 'sowing', 'sprouts'], dtype='<U23')

In [90]:
out_list = np.unique(out_list)

In [95]:
df2 = pd.DataFrame()

In [100]:
df2 = df2.assign(Plant = out_list)

In [102]:
x = df1.columns

In [115]:
for i in x:
    df2[i] = np.nan

In [116]:
df2.head()

          Plant  Jan  Feb  Mar  Apr  Sep  Oct  Nov  Dec  May  Jun  Jul  Aug
0  Asian greens  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1         Basil  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2         Beans  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3     Beetroots  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4    Broadbeans  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

In [120]:
for i in df2.Plant:
    if i in df1.column:
        df2.iloc[0] = 1

In [ ]:
df2.dropna(how='any')

In [ ]:
df2.to_csv('iteration2.csv', sep=',', encoding='utf-8')